# Pytorch가 무엇인가요?

Python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 합니다.

- NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우
- 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

# 시작하기

## Tensors

Tensor는 NumPy의 ndarray와 유사할 뿐만 아니라, GPU를 사용한 연산 가속도 지원합니다.

In [1]:
from __future__ import print_function

In [2]:
import torch

초기화되지 않은 5x3 행렬을 생성합니다.

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 8.5899e+09, 0.0000e+00],
        [8.5899e+09,        nan,        nan],
        [0.0000e+00, 0.0000e+00, 1.9849e-33],
        [1.4013e-45, 1.6255e-43, 0.0000e+00],
        [2.2181e-33, 1.4013e-45, 2.4278e-33]])


무작위로 초기화된 행렬을 생성합니다.

In [5]:
x = torch.rand(5,3)
print(x)

tensor([[0.1568, 0.1139, 0.7388],
        [0.9846, 0.7303, 0.9949],
        [0.3136, 0.8631, 0.4400],
        [0.8457, 0.0996, 0.0600],
        [0.6270, 0.2609, 0.9537]])


dtype이 long이고 0으로 채워진 행렬을 생성합니다.

In [9]:
x = torch.zeros(5,3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


데이터로부터 바로 tensor를 생성합니다.

In [11]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


또는, 존재하는 tensor를 바탕으로 tensor를 만듭니다. 이 메소드(method)들은 dtype과 같이 사용자로부터 제공된 새로운 값이 없는 한 입력 tensor의 속성을 재사용합니다.

In [13]:
x = x.new_ones(5, 3, dtype=torch.double)   
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)  

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.9928,  1.2648, -2.2121],
        [ 0.3109, -1.1087, -0.4734],
        [ 0.2967, -0.3979, -0.1550],
        [-0.4470, -0.0675,  1.0804],
        [-0.2631,  1.3075,  0.1388]])


행렬의 크기를 구합니다.

In [14]:
print(x.size())

torch.Size([5, 3])


## Operations

덧셈: 문법1

In [16]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[-0.9928,  1.2648, -2.2121],
        [ 0.3109, -1.1087, -0.4734],
        [ 0.2967, -0.3979, -0.1550],
        [-0.4470, -0.0675,  1.0804],
        [-0.2631,  1.3075,  0.1388]])
tensor([[0.1917, 0.7807, 0.8164],
        [0.2478, 0.0821, 0.5532],
        [0.2986, 0.4550, 0.1302],
        [0.8474, 0.9252, 0.2868],
        [0.7476, 0.7630, 0.3622]])
tensor([[-0.8011,  2.0455, -1.3957],
        [ 0.5587, -1.0266,  0.0798],
        [ 0.5952,  0.0570, -0.0248],
        [ 0.4004,  0.8578,  1.3672],
        [ 0.4845,  2.0705,  0.5009]])


덧셈: 문법2

In [18]:
print(torch.add(x, y))

tensor([[-0.8011,  2.0455, -1.3957],
        [ 0.5587, -1.0266,  0.0798],
        [ 0.5952,  0.0570, -0.0248],
        [ 0.4004,  0.8578,  1.3672],
        [ 0.4845,  2.0705,  0.5009]])


덧셈: 결과 tensor를 인자로 제공

In [20]:
result = torch.empty(5, 3)
print(result)
# reult는 결과 tensor로 x와 y를 더한 결과를 인자에 대입
torch.add(x, y, out=result)
print(result)

tensor([[ 0.0000e+00,  8.5899e+09, -4.9067e+12],
        [ 3.6902e+19,  3.2343e-29,  1.4013e-45],
        [-4.7082e+23,  4.5915e-41, -4.7083e+23],
        [ 4.5915e-41,  0.0000e+00,  4.2039e-45],
        [ 3.1194e+05,  4.5824e-41,  7.0065e-45]])
tensor([[-0.8011,  2.0455, -1.3957],
        [ 0.5587, -1.0266,  0.0798],
        [ 0.5952,  0.0570, -0.0248],
        [ 0.4004,  0.8578,  1.3672],
        [ 0.4845,  2.0705,  0.5009]])


덧셈: 바꿔치기(In-place) 방식

In [21]:
# y에 x 더하기
y.add_(x)
print(y)

tensor([[-0.8011,  2.0455, -1.3957],
        [ 0.5587, -1.0266,  0.0798],
        [ 0.5952,  0.0570, -0.0248],
        [ 0.4004,  0.8578,  1.3672],
        [ 0.4845,  2.0705,  0.5009]])


NumPy의 인덱싱 표기 방법을 사용할 수도 있습니다.

In [25]:
print(x)
print(x[:,1])
print(x[0:2,1])

tensor([[-0.9928,  1.2648, -2.2121],
        [ 0.3109, -1.1087, -0.4734],
        [ 0.2967, -0.3979, -0.1550],
        [-0.4470, -0.0675,  1.0804],
        [-0.2631,  1.3075,  0.1388]])
tensor([ 1.2648, -1.1087, -0.3979, -0.0675,  1.3075])
tensor([ 1.2648, -1.1087])


크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶을 때, torch.view 를 사용합니다.

In [26]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # 사이즈가 -1인 경우 다른 차원들을 사용하여 유추합니다.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


만약 tensor에 하나의 값만 존재한다면, .item() 을 사용하면 숫자 값을 얻을 수 있습니다.

In [27]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.8790])
-0.8790178298950195


# Numpy 변환 (Bridge)

Torch Tensor를 NumPy 배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽습니다.

Torch Tensor와 NumPy 배열은 저장 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

## Torch Tensor를 NumPy 배열로 변환하기

In [28]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [31]:
b = a.numpy() # Tensor를 numpy로 변환
print(b)

[2. 2. 2. 2. 2.]


In [32]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


## NumPy 배열을 Torch Tensor로 변환하기

NumPy(np) 배열을 변경하면 Torch Tensor의 값도 자동 변경

In [33]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제외한 CPU 상의 모든 Tensor는 NumPy로의 변환을 지원하며, (NumPy에서 Tensor로의) 반대 변환도 지원합니다.

## CUDA Tensors

.to 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있습니다.

In [35]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.
if torch.cuda.is_available():
    device = torch.device("cuda")          # CUDA 장치 객체(Device Object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 바로(directly) tensor를 생성하거나
    x = x.to(device)                       # 단지 ``.to("cuda")`` 라고만 작성하면 됩니다.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!